### ISSUE TITLE
Abandoned?

### ISSUE THREAD

**Issue by vinnyrose** [FontCustom/fontcustom#321]
@kaizau @endtwist,

This library appears to be abandoned. Can you confirm if you are no longer maintaining this library? Is there a possibility of handing over to new maintainers?

Best

**Comment by kaizau** [comment]
Sadly accurate. Can't speak for @endtwist but it's not a personal priority at the moment. Considering the sheer number of PRs and forks here, that's not an ideal state of affairs.

@endtwist How's your bandwidth these days? Perhaps we draft up a transition plan?

**Comment by kaizau** [comment]
The state of frontend tooling has changed quite a bit since we started. Even in 2013, we considered making a [Node conversion](https://github.com/FontCustom/fontcustom/issues/146). And if we started fresh in 2016, there's no chance this wouldn't be a npm module. 

So my inclination would actually be to rapidly sunset the current version of FontCustom and replace it with a rewrite. A final PR / bugfixes release would be ideal for those who are committed to ruby.

**Comment by endtwist** [comment]
@kaizau Yes, same here. It's not been a priority and I've begun to stray away from using fonts as a storage/display method for icons (switching over to, often, SVG's `use`).

That being said, it's clear that Font Custom is still valued greatly (with 20 PRs and 82 issues open).

@kaizau I think it would be worthwhile to draft up a plan to add some core contributors, sunset the gem, and make a plan for a Node-based implementation.

**Comment by jpotterm** [comment]
In case it helps, there is a Node project [grunt-webfont](https://github.com/sapegin/grunt-webfont) that looks like it may have a similar implementation (it has a FontForge backend). Maybe you could combine forces with them?

Personally I think it'd be better to have one NPM module with all the business logic and then have other NPM modules that are thin wrappers for command line, Grunt, Gulp, etc.

**Comment by JakeBeresford** [comment]
I will be working on resolving open issues & merging PRs, then releasing a new major in the coming weeks.

Ongoing support will be limited, and I would recommend using SVG rather than icon fonts if possible. I understand that others may have similar constraints as I do, which is my motivation to release an update to this project.

Thanks for your patience.
